### PR TITLE
Update symlinked repos

### PR DESCRIPTION
**Pull request by rpadrela**
Update to symlink brisk-dotnet and flux-dotnet from coherence, not from piot.

Linting.

### CODE REVIEW

**Comment by rpadrela** [comment]
@kingstone426 , any clue what the build error is?

**Review by kingstone426 — APPROVED** [review]
I removed the outdated repo secret in settings and re-run the build so CI works now.

**Comment by ottov1** [comment]
Was the binary file `src/coherence/coherence` submitted by mistake?

**Comment by rpadrela** [comment]
> Was the binary file `src/coherence/coherence` submitted by mistake?

uhhh, definitely! Thanks for spotting that!

**Pull request merged**
